### ISSUE TITLE
Switch between color and white

### ISSUE THREAD

**Issue by Sanderbloem050** [bokub/rgb-light-card#11]
Is there a possibility to switch between color and white mode a possibility to switch between color and white mode?

**Comment by bokub** [comment]
I don't understand your question, please explain what you have in mind

**Comment by Sanderbloem050** [comment]
In this case it is a RGB W strip and in the native app it had 3 modes; White, Color, Scenes. Seen attachment below.

What would be great if there is a switch or an "Color" icon that goes to the white mode.

![IMG_20200203_100900](https://user-images.githubusercontent.com/58403275/73639939-a3b2b900-466d-11ea-941c-7bba8a0015c0.jpg)

**Comment by bokub** [comment]
This card is nothing more than an interface for the [`light.turn_on`](https://www.home-assistant.io/integrations/light#service-lightturn_on) service.

The first thing you have to do is trying to achieve what you want using the `light.turn_on` service, and I can't help you because I don't know how your light works

When you figure the right options, you can start configuring the card

**Comment by bokub** [comment]
Maybe `white_value` or `color_temp` are the options you need, but I can't be sure of that

**Comment by Sanderbloem050** [comment]
Your the best! I will look in to that.
It already solved the issue that I couldn't control my Tuya RGB lights with HA 😉

**Comment by Sanderbloem050** [comment]
brightness: 100
color_temp: 1000

This is what worked for me. switch between colors and in this example white mode..

Thank you!

**Comment by BenJamesAndo** [comment]
This is what worked for me. It switches to white color mode and sets the brightness
```
type: custom:rgb-light-card-feature
entity: light.white_noise_machine
  - brightness_pct: 50
    white: true
    label: White Mode
```

then when I have
```
  - rgb_color:
      - 136
      - 198
      - 237
    brightness_pct: 20
    transition: 1
```

clicking between the both switches between white mode and RGB mode.
