### ISSUE TITLE
Call a service from the tap acton (type)

### ISSUE THREAD

**Issue by dklemm** [bokub/rgb-light-card#12]
It would be really useful to be able to call a service instead scene or script. Scripts and scene can be triggered from call-service.

This is how entity-button works.

tap_action:
  action: call-service
  service: hue.hue_activate_scene
  service_data:
    group_name: Family Room
    scene_name: Ibiza

I've created a fork here with call-service https://github.com/dklemm/rgb-light-card.  Ideally scene and script would be removed but I've left them there for backward compatibility

**Comment by bokub** [comment]
Hi,
That is a great idea ! :+1: 

Could you please submit a pull request ?
