### ISSUE TITLE
Card doesn't work in HA 0.106b0

### ISSUE THREAD

**Issue by noxhirsch** [bokub/rgb-light-card#15]
Hi,
the light card doesn't work in HA 0.106b0 and creates this error in console:
`Uncaught (in promise) http://XXXXXXXXXXX/community_plugin/rgb-light-card/card.js`

I think it has something to do with the changes for custom cards:
https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes/

Thank you!
Nico

**Comment by bokub** [comment]
Can you please open your JS console (F12 key) and post a screenshot?

Thanks

**Comment by noxhirsch** [comment]
Update: I found an additional 404 error in the top of the console (I just didn't see it because of the many card errors in 0.106b0) 🤦‍♂️ 
HACS somehow removed the folder and card.js of rgb-light-card and even didn't reinstalled it. Then I added it manually. Now I get this error:
![rgb-card](https://user-images.githubusercontent.com/30938717/74981915-64d57f00-5433-11ea-8620-a49e966bc835.JPG)

**Comment by noxhirsch** [comment]
And this is the card:
![image](https://user-images.githubusercontent.com/30938717/74981970-86cf0180-5433-11ea-8975-983a28f6847c.png)

**Comment by Woodcat64** [comment]
Had similar issue yesterday. Previously working Rgb-light-card (v1.4.0) would not work. 
"Custom element doesn't exist: rgb-light-card"

Tried downgrading to v1.3 and v1.2 and when that did not work I uninstalled it, but it would not install back.  It said it is installed, but no rgb-light-card directory was created.
Manually made directory and copied in card.js file. 

I'm still on Home Assistant 0.105.5 with HACS 0.21.5

**Comment by bokub** [comment]
Can you please uninstall the card, then install v1.4.1, and tell me if your problems are solved?

Thanks a lot

**Comment by Woodcat64** [comment]
Yes, It's working for me.
Thank you

**Comment by bokub** [comment]
That's great to hear 😌 
I'm waiting for @noxhirsch to answer before closing the issue

**Comment by noxhirsch** [comment]
Sorry for the late reply - it was night time in Germany 😴
Now I've tested v1.4.1 and it's working fine for me again. Thank you very much for your fast fix (despite that this HA version is still beta)!
