### ISSUE TITLE
Android app issue: Invalid type 'call-service' for colors[x]

### ISSUE THREAD

**Issue by akarpenkoua** [bokub/rgb-light-card#18]
Good day and thank you for this card. At browser version all is warking good, but mobile app for Android is giving me the error 
"Android app issue: Invalid type 'call-service' for colors[x]"

This is only for call-service type. 
Light type works super.

**Comment by bokub** [comment]
Hi,
This is most likely a cache issue: your android app still uses the old version of the card, which didn't support the `call-service` type.

You have 2 options
- Wait a few days (7 days in worst case scenario)
- Force a cache invalidation by adding some URL param to the card file in your raw config editor, for example: `/community_plugin/rgb-light-card/card.js?v=1.5.0`

If you choose the second option, HACS will think you didn't add the card to your Lovelace resources, and will display a red icon, but you can revert it later

**Comment by akarpenkoua** [comment]
I've just reinstalled the app and all is working now. 
Thank you once again!
