### ISSUE TITLE
Cannot assign to read only property 'colors' of object '#<Object>'

### ISSUE THREAD

**Issue by Griizly** [bokub/rgb-light-card#19]
Hello, 

I'm using home assistant on a rpi 4 - 2GB ( Home Assistant 0.106.0 )

and i'm facing this issue, can you please help me ?
![lampe erreur](https://user-images.githubusercontent.com/20046947/75487782-5cd78b00-59af-11ea-894e-f5abf35efc75.png)

**Comment by bokub** [comment]
What version of the card are you using?

**Comment by Griizly** [comment]
Hello, I'm at work right now but I was using the latest version from the community store

What I did yesterday was to replace the path to the js file with this https://cdn.jsdelivr.net/npm/rgb-light-card and it worked.

Will try again later with the path to the js file

**Comment by bokub** [comment]
Did the error occur after an update, or is it the first time you use the card ?

**Comment by Griizly** [comment]
first time using the card, the plugin was in the right folder with the right path.

What i'm actually doing is migrate my home assistant server running from an very old laptop to a raspberry pi.
Restore a snapshot never worked for me ( i think this is because laptop is running 64bit version of HASS and raspberry 32bit ), the home assistant instance never restart so what I did was to manualy copy/paste my old config file to the raspberry.

that was a bit of a hassle but it worked except for the rgb light card with the js file

tonight I will delete the rgb light card folder, restart HASS and reinstall it again.

If it doesn't work I will provide as much info ( logs etc ) as possible :)

Thanks for replying to me ;)

**Comment by phil-schneider** [comment]
Hello,
I have the same problem.
It was running fine without any problems. I did not change any config.
I might have updated to the newest version with HACS.
What am I missing here?
Thanks

**Comment by bokub** [comment]
It might be the changes from the 0.106 version..
Can you open the JavaScript console (F12 key) and post a screenshot of it? 
Thanks

**Comment by phil-schneider** [comment]
strange. Now it is working again. I updated HA to 0.106.1 also also reinstalled this plugin.

Thanks for your help
