### ISSUE TITLE
[Feature Request] Named Colors

### ISSUE THREAD

**Issue by brianhanifin** [bokub/rgb-light-card#2]
I notice that you can set a named icon_color. It would be nice if you could extend that ability to the light color as well.

Example:
```
colors:
  - red
  - green
  - blue
```

I realize this isn't exactly a simple request. Since, code would have to be written to convert a name to an RGB value.

Here are a few reference links to take a look at.
[HTML Color Names Reference](https://htmlcolorcodes.com/color-names/)
[HTML Color Names/RGB Values in JSON format](https://jonasjacek.github.io/colors/data.json)
[JSON Lint to make the JSON readable](https://jsonlint.com/)

**Comment by bokub** [comment]
Thanks for your references, but that won't be necessary, as you can already use something like this:

```yaml
colors:
  - color_name: red
  - color_name: green
  - color_name: blue
```

For information, `color_name` is an option of the [`light.turn_on` service](https://www.home-assistant.io/integrations/light/#service-lightturn_on)

**Comment by brianhanifin** [comment]
I looked for that option ... ok, now I fully grasp the meaning of “All options of light.turn_on“. It seems obvious in retrospect. Thanks.
