### ISSUE TITLE
cloud not find rgb-light-card

### ISSUE THREAD

**Issue by plutosherry** [bokub/rgb-light-card#21]
i have been add the resources like it:
`  # RGB Light Card
    url: /local/custom-lovelace/rgb-light-card/rgb-light-card.js
    type: js`

but lovelaceUI display the error :

`Custom element doesn't exist: rgb-light-card.
type: 'custom:rgb-light-card'
entity: light.esp8266_leds
colors:
   rgb_color:
       255
       127
       255
    brightness: 220
    transition: 1
   hs_color:
       60
       30
    icon_color: '#fff8b0'`

PLZ help！！！

**Comment by bokub** [comment]
It looks like you didn't install the card, or used a wrong url in the resource

Did you install the card? How?
