### ISSUE TITLE
Does not work on default mobile app UI

### ISSUE THREAD

**Issue by dochost** [bokub/rgb-light-card#22]
When using the default lovelace UI for mobile app the custom card does not show colors but instead shows the original switch label instead

**Comment by dochost** [comment]
The issue is only on Android app and I'm not sure if it's related to the app

![Screenshot_20200405-233026](https://user-images.githubusercontent.com/41865273/78509253-93b27500-7795-11ea-9359-0bbc87a5c291.jpg)

**Comment by bokub** [comment]
I'm using the android app and it works perfectly (it's basically a web browser)

It might be a cache issue, can you reload a few times?

**Comment by dochost** [comment]
I tried to logoff and login it didn't work.

But when I test via the web browser it works perfectly, very weird...

I'll close this issue.

Thank you for the quick response
