### ISSUE TITLE
"Double" switch in lovelace

### ISSUE THREAD

**Issue by vencakratky** [bokub/rgb-light-card#23]
Hi all, please can somebody tell me, why i have "double" switch in lovelace? 
![rgb_lampa1](https://user-images.githubusercontent.com/54419577/81613623-1787fe80-93df-11ea-9f45-e68f62332e4b.jpg)
There is my code:
https://pastebin.com/HCXCcNib 
I believe the mistake will be on my side
rgb-light-card i use per HACS
Thank you for experiences

**Comment by bokub** [comment]
It's the [header toggle](https://www.home-assistant.io/lovelace/entities/#show_header_toggle) ! 

Add `show_header_toggle: false` either in the first or the last line

**Comment by vencakratky** [comment]
As I say, it's my Mistake :smiley: 
Thank You!
