### ISSUE TITLE
Feature Request: Name or Label

### ISSUE THREAD

**Issue by hathalud** [bokub/rgb-light-card#24]
I have a pretty complex lovelace layout. And while I understand the intention for there to be a toggle above the rgb card, on my system it's not present "above". Instead all controls for a single light are on a "swipe" card. I'm doing it this way to reduce screen real-estate. But when you're looking at 9 different rgb cards, it's a little confusing to be sure you're about to tap the right one.   It'd be nice if we could toggle on displaying the name/label of the card and be able to define the name/label. Currently I'm using the "justify" option to stagger them some, but that's not an ideal solution. 

A video capturing my current setup. [https://drive.google.com/file/d/16W_0IjnJtxiWqPVsa4l3Jy3UvC7Xr4d-/view?usp=sharing](https://drive.google.com/file/d/16W_0IjnJtxiWqPVsa4l3Jy3UvC7Xr4d-/view?usp=sharing)

**Comment by bokub** [comment]
I don't think I'll implement this label thing, so I'm closing the issue for the moment

Sorry about that
