### ISSUE TITLE
Feature Request: Color names and brightness control

### ISSUE THREAD

**Issue by toshymaeda** [bokub/rgb-light-card#26]
1) Possibility to define names to each color (and maybe appear in a tooptip in the card)
2) Control brightness of the light with a slider component in the card.

**Comment by bokub** [comment]
For the slider, you can already combine rgb-light-card, slider-entity-row, and [stack-in-card](https://github.com/custom-cards/stack-in-card) to do great things

For example, with [this configuration](https://nopaste.ml/?l=yaml#XQAAAQC2AQAAAAAAAAA6HkpEA1wCjsvRKoQJj8WV3kBdC75LL9h/zd64IAhDsT3A/MyOtPCKh3nm8rII3oNQ4T6BNvVaqNxKTlVg+t+UPt/vkQsQ5nUPYIsYa96RgKRVFUaTdgQ1vmlDo1Oc85GtPbvwrqu44ypREo2r4MCs2UrFVWgfl4p5BHi5EZhdqCoEDPnW7zvNS75VObdQbBVpMCH7luirF/8fAAmWWNtEuhKsdmk+kUCift4vP1Pd+CjRPvTgInm///D+SvY=):

![image](https://user-images.githubusercontent.com/17952318/91017678-db278980-e5ee-11ea-8b58-60f80374fdc6.png)

**Comment by bokub** [comment]
For the color names, do you just want a tooltip to know the name of your colors?
How would it work on mobile?

**Comment by mwitkow** [comment]
+1 to name

A small text above/below similar to https://github.com/benct/lovelace-multiple-entity-row would be fantastic!

**Comment by bokub** [comment]
> A small text above/below

I could do something like this... I'll try some things

**Comment by dominikheinz** [comment]
This is very interesting, any updates on this yet?

**Comment by bokub** [comment]
I have lots of projects going on, but this is definitely planned for the weeks to come :tada: 

Or if anyone wants to give it a try, PR are welcome
