### ISSUE TITLE
More color icon styles?

### ISSUE THREAD

**Issue by dominikheinz** [bokub/rgb-light-card#27]
It would be a great addition if the user could chose between different styles for the color icons in the card.
So, instead of only having the circles to indicates the color, we could also e.g. have bars to indicate the color. 
Here is an example screenshot, what I mean:

![example](https://user-images.githubusercontent.com/32770080/93692674-539e3f00-faf6-11ea-987e-07fe1641464e.png)

Would it be possible to add this?

**Comment by bokub** [comment]
Hi,

Thank you for the suggestion, but that's not the vision I have for this card right now.

However, if you really want this feature, you can download the card, tweak the CSS, and use this modded version in your own Home Assistant
