### ISSUE TITLE
Warning: The value of entities.1 is not supported by the UI editor?

### ISSUE THREAD

**Issue by dominikheinz** [bokub/rgb-light-card#28]
After installing this card via HACS I manually created a new card.
However, even tho the card works flawlessly (I can control the light and swithc colors), - I am prompted with the following warning when editing the card:

![warning](https://user-images.githubusercontent.com/32770080/95269373-8d32b200-0839-11eb-8950-e6f176874404.PNG)

What is causing this warning? How can I get rid of it, if possible?

**Comment by bokub** [comment]
The warning is clear: 

The UI editor is unavailable for this custom card. You can still use the YAML editor. That's absolutely normal, I haven't coded any UI editor for this card.

I have no idea if you can get rid of it
