### ISSUE TITLE
Haptics support

### ISSUE THREAD

**Issue by agneevX** [bokub/rgb-light-card#29]
Hi!

Love your card. Its perfect for my lamps. However its missing haptic support. 

I would appreciate it very much if you could add it, thanks.

**Comment by bokub** [comment]
Hi,

Do you know any custom card which implement haptic support? That would help a lot

**Comment by agneevX** [comment]
`button-card` - https://github.com/custom-cards/button-card/pull/123

**Comment by bokub** [comment]
That's a great idea !

**Comment by agneevX** [comment]
You can more info here: https://companion.home-assistant.io/docs/integrations/haptics/

**Comment by bokub** [comment]
I won't be able to code this as I don't have an Apple device to test, but I'll leave this issue open in case someone wants to give it a try

**Comment by agneevX** [comment]
@bokub I'm willing to test this, if you're up for it

**Comment by bokub** [comment]
Sure, go ahead 👍

**Comment by agneevX** [comment]
I meant I would volunteer to test your code.

**Comment by agneevX** [comment]
@bokub vibrations should work on Android with:

```yaml
tap_action:
  haptic: medium
  action: more-info
```

Hopefully if https://github.com/home-assistant/android/issues/1091 is resolved, haptics should work on Pixel devices, which IIRC support haptics on Android.

**Comment by bokub** [comment]
I finally changed my phone for one that supports haptics!

Version 1.12.0 now integrates haptics support
