### ISSUE TITLE
[Feature Request] Enable ability to configure card from card picker

### ISSUE THREAD

**Issue by TJohnson93** [bokub/rgb-light-card#33]
Just a user-friendly feature request to enable to the ability to configure this awesome card from the lovelace card picker? Apparently a few lines of code, not sure how realistic the "easiness" is.

https://www.reddit.com/r/homeassistant/comments/jovt1l/usedevelop_custom_cards_your_card_could_be_in_the/?utm_source=share&utm_medium=web2x&context=3

**Comment by bokub** [comment]
That's a good idea! Will do soon

**Comment by bokub** [comment]
Done in [1.9.0](https://github.com/bokub/rgb-light-card/releases/tag/1.9.0) :tada:
