### ISSUE TITLE
Colors are not hidden while entity is unavaliable

### ISSUE THREAD

**Issue by peetereczek** [bokub/rgb-light-card#34]
In my opinion block of colours should be hided, while light entity is unavaliable (not only while off):

![image](https://user-images.githubusercontent.com/42431204/102700462-d8137180-424d-11eb-924d-69a43d7968f4.png)

My setting:
type: entities
entities:
  - entity: light.living_room_rgb
  - type: 'custom:rgb-light-card'
    entity: light.living_room_rgb
    justify: center
    hide_when_off: true
    colors:
      - rgb_color:
          - 255
          - 0
          - 0
        brightness: 200
        label: Czerw
      - rgb_color:
          - 0
          - 0
          - 255
        brightness: 200
        label: Bieski
      - rgb_color:
          - 0
          - 255
          - 0
        brightness: 200
        label: Zielony

**Comment by bokub** [comment]
Yep, I'm having the same issue. I'll fix it when I'll have some free time 👍

**Comment by bokub** [comment]
Fixed in 1.8.0 :tada:
