### ISSUE TITLE
[Feature Request] entity name on left side, buttons on right side

### ISSUE THREAD

**Issue by Chourrage** [bokub/rgb-light-card#36]
I'd like to have an option to show the name and icon on the left side, like a with a normal entity card, and then the colour buttons on the right side. I don't know if it's easy to implement but if it's possible it would be awesome!

Thanks for the great work, I've been using this a lot lately and it's great!

![How it would look like](https://user-images.githubusercontent.com/56000193/104110776-2b239600-52db-11eb-95f5-9203e652cab7.png)

**Comment by bokub** [comment]
This what I was able to to using [this configuration](https://nopaste.ml/?l=yaml#XQAAAQCrAQAAAAAAAAA6HkpEA1wDNFkB3qBVQRH+vrmAEjIe80DETAjV4yZBLXnDLBUpy1R9gsrzUoAkL95fegRJ/nLZr/DP9pyFdNUqVAxJ2huTsCL7XmYt7F1/nrWbrtA4Yfph87xwGzkAcjurmufV+IyhZuj5Q7eIVMA32agHbvavcn86y2H29mB7j+VBVn2g0h6ik+vjbZZeDXEwnlkFBYjc8Jy2MwaQus2qt4+7XLQb8Z3ZWE+gaOWjF0mZJbTWZoD/hOevouAmOPH/6UN7gA==) and the "[stack-in-card](https://github.com/custom-cards/stack-in-card)" card.

I could not remove the switch, but would that suit you?

![image](https://user-images.githubusercontent.com/17952318/104132496-ee5cab00-537d-11eb-8d8b-d2ae5a412bac.png)

**Comment by Chourrage** [comment]
Great, yes that's exactly what I was looking for! Thanks a lot. I tried it with a normal horizontal stack but it didn't look as good. I thought about combining it with the slider, but didn't think it would work that well. This solution works great. Thanks a lot!
