### ISSUE TITLE
[Feature request] include default preset color palette(s)

### ISSUE THREAD

**Issue by sphanley** [bokub/rgb-light-card#40]
It would be really nice if there were some stock default color palettes available without having to manually define them, e.g. a range of whites or a range of common basic colors. This would make it much easier to quickly try out the card. 

If I get enough downtime, I may take a stab at implementing this, but thought I'd throw it out here in case you or anyone else feels like it's worth picking up!

**Comment by bokub** [comment]
Are you thinking about presets that you can choose directly in the card configuration? Or just examples in the README ?

**Comment by bokub** [comment]
I'm currently working on a default configuration when adding the card from the Lovelace UI.

@sphanley Did you manage to create some default palettes that I could use?

**Comment by sphanley** [comment]
Nope, got sidetracked and never ended up picking this up. Excited that you might have something in the pipeline!

**Comment by bokub** [comment]
All right then, I've added a default config in [1.9.0](https://github.com/bokub/rgb-light-card/releases/tag/1.9.0) :tada:
