### ISSUE TITLE
[Idea] Add slider in the card.

### ISSUE THREAD

**Issue by pinkfloydFR** [bokub/rgb-light-card#45]
Sorry if this not the right way, but this is an idea, not an issue.

It would be nice if you can add slider in yours cards, like this, when using "hide_when_off"  you can show the icon/shortcut color and a slider...

Hope my explanation was clear.

Thanks for this wonderful card by the way !

![SNAG-0050](https://user-images.githubusercontent.com/49475899/118288647-e69c4700-b4d4-11eb-875c-d0c25121d9df.png)

**Comment by bokub** [comment]
The `slider-entity-row` already does that, as explained in #35 

Does it meet your needs ?

**Comment by pinkfloydFR** [comment]
You right, my bad, was my yaml file miss configurated. Thanks for the great job !
