### ISSUE TITLE
Light switches not updating

### ISSUE THREAD

**Issue by hocahoon** [bokub/rgb-light-card#56]
Hello!

First let me thank you for a fantastic card and for sharing it.

I've finally got it setup with everything working, when I toggle a light on, the toggle immediately reverts back to the off position and 5-10 seconds later back to the on position.  The lights operate perfectly fine, but it's like there's a delay in the ui and it's waiting to ping the bulbs for the toggle to stay on.

This does not happen with the built in entities card.

**Comment by bokub** [comment]
If you go to the "Services" page and toggle a light with the `light.turn_on` service, do you encounter the same issue?

**Comment by bokub** [comment]
I'm closing this issue. Don't hesitate if you have other questions.
