### ISSUE TITLE
Custom element doesn't exist: rgb-light-card.

### ISSUE THREAD

**Issue by markusmauch** [bokub/rgb-light-card#65]
Apperars with version 2022.8

**Comment by Jhorts** [comment]
I too have this issue. The card does not appear in the picker and manual entry states "Custom element doesn't exist: rgb-light-card."
![error](https://user-images.githubusercontent.com/7142685/187057079-37015c80-df7c-4589-8cda-65bcf0b43728.PNG)

**Comment by bokub** [comment]
How did you install the card?

**Comment by Jhorts** [comment]
Installed via HACS. I’m new to HA, but as I understand, I should be able click “download” in HACS and the card show up in the picker. If I click “open source” in HACS, I get a 404 error.

**Comment by bokub** [comment]
Did you click the "reaload UI" button after installing the card? (you can unsinstall and install again if you didn't)

**Comment by ksbarnes** [comment]
For what it's worth, I'm also seeing this behavior. Attempting to uninstall/reinstall does not resolve the issue (including reload UI, incgonito mode, other devices, etc.).

I can confirm the files are downloading to /config/www/community/rgb-light-card like expected. It's just almost like the card isn't getting enabled for frontend use.

**Comment by ksbarnes** [comment]
Updated to the recently released HACS 1.27.1, and this issue has gone away for me.

**Comment by Jhorts** [comment]
I fairly certain I did reload the UI and even did a full restart of HAOS. I installed and HACS yesterday so I should be on the latest version. I’ll try again today and report back.

**Comment by bokub** [comment]
@Jhorts sorry but I tried to reproduce the issue and didn't succeed.

As pointed by @ksbarnes , did you try incognito mode, or using another device?

Can you try Ctrl+Shift+R to hard-refresh your browser?

I really doubt this card has anything to do with your problem, which looks related to Home Assistant or HACS....

**Comment by Jhorts** [comment]
I had a pending HACS update today. Updated to 1.27, removed the card and other resources and started from step one. Seems to work now. Thanks for your help.

**Comment by and7ey** [comment]
Had the same problem. Fixed by adding 
```
  - url: /local/community/rgb-light-card/card.js
    type: module
```
to `configuration.yaml`. Strange, but HA said that another path should be used (which is wrong).
