### ISSUE TITLE
Understand that light group is a light

### ISSUE THREAD

**Issue by alexandrechoske** [bokub/rgb-light-card#67]
![image](https://user-images.githubusercontent.com/47279355/196080824-c505aa49-564d-464a-a70b-e27a8d50b376.png)

Hi, an really nice upgrade could be a light group be interpreted as a light, now we can not use like that.

Thanks!

**Comment by bokub** [comment]
Hi,
My card is supposed to work with light groups, but light groups usually start with `light.`

Can you please show the entities in your group?

**Comment by alexandrechoske** [comment]
Hi! Thanks for reply!

As you can see it is only lights inside.

![image](https://user-images.githubusercontent.com/47279355/196165438-f6d0a502-c658-479c-bfd9-2896140eb68a.png)

**Comment by bokub** [comment]
Can you please try to create a **new** light group using the UI and check the ID of this new group?

**Comment by alexandrechoske** [comment]
Yeah you are right, in the UI HA creates the group as a light.something :/ and now it works fine.

![image](https://user-images.githubusercontent.com/47279355/196171154-78557672-53ec-49b4-b5b8-cdcbaa3130df.png)

**Comment by bokub** [comment]
Great ! I'm closing this issue
