### ISSUE TITLE
White color on RGB strip

### ISSUE THREAD

**Issue by maciekelga** [bokub/rgb-light-card#73]
Hi

I have a question related to white color on RGB led strip.

I have config as below:

Type: entities
show_header_toggle: false
entities:
  - type: custom:rgb-light-card
    entity: light.jadalnia_swiatlo_rgb
    colors:
      - rgb_color:
          - 255
          - 255
          - 255
        brightness: 255
        transition: 1

Other colors like red or blue etc working well but whit is not working. How to do this in correct way?

**Comment by bokub** [comment]
I don't understand what is not working.

Before creating a card, did you manage to do what you want using the `light.turn_on` service?

**Comment by maciekelga** [comment]
It is solved. When I used rgb_color with 3x255 by default separete white channel were called instrad of make white from RGB. I'm using RGB and I had to use configuration as follow to get white from RGB strip:

Type: custom:rgb-light-card
entity: light.jadalnia_swiatlo_rgb
colors:
rgbw_color:
255
255
255
0
brightness: 255
transition: 1
