### ISSUE TITLE
control separate LEDs for R,G,B

### ISSUE THREAD

**Issue by wspeth** [bokub/rgb-light-card#76]
Boris, I would kindly ask for your advice on how to control devices that show up as separate entities for the colors, like
light.0x00124b002a5ecb75_l1, light.0x00124b002a5ecb75_l1, light.0x00124b002a5ecb75_l3, light.0x00124b002a5ecb75_l4 (RGBW)
My first idea is to change card.js, replace line   134      this._hass.callService('light', 'turn_on', serviceData); by  four calls while changing
const serviceData = {  entity_id: this.config.entity,  ...color,
to something like 
const serviceData = {  entity_id: this.config.entity.replace(/.$/,str(i)), color[i] when looping i from 1 to 4

would you agree or can you envisage a simpler approach?

**Comment by bokub** [comment]
Hi @wspeth,

Why don't you create a [script that accepts variables](https://www.home-assistant.io/integrations/script/#passing-variables-to-scripts), then call this script whenever you click on a color circle?

**Comment by wspeth** [comment]
good advice, greatly appreciated. After a day of fiddling around I am getting closer to it. Now I am stuck again
      - type: call-service
        service: script.i_colors
        service_data_template:
          device_id: "{{ device }}"
          brightness: [0,0,0,0]

renders "undefined error, brightness is undefined".
going with service_data instead of service_data_template it does not substitue device.
Also tried to enclose [0,0,0,0] by {{ }} or {% %}. Neither works,

**Comment by bokub** [comment]
Hello,

You should use `service_data` to pass variables to your service, not `service_data`.
