### ISSUE TITLE
[Feature Request] Option to show icons only when light is on

### ISSUE THREAD

**Issue by Yunus1903** [bokub/rgb-light-card#8]
As the title says, I would like to have a option to have the icons only show when the light is on.

**Comment by bokub** [comment]
Can't you already achieve this result with the [Conditional Card](https://www.home-assistant.io/lovelace/conditional/) ?

**Comment by Yunus1903** [comment]
I never thought of that.
Thanks!

**Comment by bokub** [comment]
By the way, you can now use the `hide_when_off` parameter to do that
