### ISSUE TITLE
Allow RGB card to work with groups (seems to work fine)

### ISSUE THREAD

**Issue by dave-vsdevs** [bokub/rgb-light-card#80]
"card.js" line 85

        if (config.entity && (config.entity.indexOf('light.') !== 0 && config.entity.indexOf('group.') !== 0)) {
            throw new Error(`Entity '${config.entity}' must be a light/group`);
        }

I am using the https://community.home-assistant.io/t/auto-light-grouping/516373 auto grouping blueprint because I did not want to manually maintain groups.  Making the change above seems to work fine for groups.

There might be some reason this causes problems further down the line but seems ok so far

I see this is a duplicate of #67 and a few others.   But maybe the code will help somebody.   Thanks for the CARD!

**Comment by bokub** [comment]
Sorry for the delay to answer your issue.

If you want to use this card with anything other than an entity starting with  `light.`, just use the `type: action` to trigger whatever you want when you click on the color. The card won't show any error, and you'll be able to turn your lights on.
